services:
  - type: web
    name: genai-secure-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 --threads 8 -b 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
